version: '3'

services: 
  web:
    build: ./client
    image: contest-board-grpc-vue-client:v1
    ports: 
      - 3000:3000
    restart: unless-stopped
    networks:
      - grpc-contest-board
  proxy:
    build: ./envoy
    image: contest-board-grpc-envoy:v1
    ports: 
      - 8080:8080
    restart: unless-stopped
    networks: 
      - grpc-contest-board
  server:
    build: ./server
    image: contest-board-grpc-server:v1
    restart: unless-stopped
    networks:
      - grpc-contest-board
networks:
  grpc-contest-board:
    driver: bridge